//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.4927.
// 
#pragma warning disable 1591

namespace CarritoDeCompras_2012.CS.ProxyVentasWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4918")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VentasWSSoap", Namespace="localhost/VentasWS.asmx")]
    public partial class VentasWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HolaDesdeVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarVentaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VentasWS() {
            this.Url = global::CarritoDeCompras_2012.CS.Properties.Settings.Default.CarritoDeCompras_2012_CS_ProxyVentasWS_VentasWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HolaDesdeVentasCompletedEventHandler HolaDesdeVentasCompleted;
        
        /// <remarks/>
        public event AgregarVentaCompletedEventHandler AgregarVentaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/VentasWS.asmx/HolaDesdeVentas", RequestNamespace="localhost/VentasWS.asmx", ResponseNamespace="localhost/VentasWS.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HolaDesdeVentas(CarritoItem[] listado) {
            object[] results = this.Invoke("HolaDesdeVentas", new object[] {
                        listado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HolaDesdeVentasAsync(CarritoItem[] listado) {
            this.HolaDesdeVentasAsync(listado, null);
        }
        
        /// <remarks/>
        public void HolaDesdeVentasAsync(CarritoItem[] listado, object userState) {
            if ((this.HolaDesdeVentasOperationCompleted == null)) {
                this.HolaDesdeVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHolaDesdeVentasOperationCompleted);
            }
            this.InvokeAsync("HolaDesdeVentas", new object[] {
                        listado}, this.HolaDesdeVentasOperationCompleted, userState);
        }
        
        private void OnHolaDesdeVentasOperationCompleted(object arg) {
            if ((this.HolaDesdeVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HolaDesdeVentasCompleted(this, new HolaDesdeVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/VentasWS.asmx/AgregarVenta", RequestNamespace="localhost/VentasWS.asmx", ResponseNamespace="localhost/VentasWS.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarVenta(Cliente cli, CarritoItem[] listado) {
            object[] results = this.Invoke("AgregarVenta", new object[] {
                        cli,
                        listado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarVentaAsync(Cliente cli, CarritoItem[] listado) {
            this.AgregarVentaAsync(cli, listado, null);
        }
        
        /// <remarks/>
        public void AgregarVentaAsync(Cliente cli, CarritoItem[] listado, object userState) {
            if ((this.AgregarVentaOperationCompleted == null)) {
                this.AgregarVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarVentaOperationCompleted);
            }
            this.InvokeAsync("AgregarVenta", new object[] {
                        cli,
                        listado}, this.AgregarVentaOperationCompleted, userState);
        }
        
        private void OnAgregarVentaOperationCompleted(object arg) {
            if ((this.AgregarVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarVentaCompleted(this, new AgregarVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4918")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="localhost/VentasWS.asmx")]
    public partial class CarritoItem {
        
        private int cantidadField;
        
        private int idProductoField;
        
        private string nombreProductoField;
        
        private double precioUnitarioField;
        
        private double precioTotalField;
        
        /// <comentarios/>
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <comentarios/>
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
            }
        }
        
        /// <comentarios/>
        public double PrecioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
            }
        }
        
        /// <comentarios/>
        public double PrecioTotal {
            get {
                return this.precioTotalField;
            }
            set {
                this.precioTotalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4918")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="localhost/VentasWS.asmx")]
    public partial class Cliente {
        
        private string nombreField;
        
        private string apellidoField;
        
        private string emailField;
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4918")]
    public delegate void HolaDesdeVentasCompletedEventHandler(object sender, HolaDesdeVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4918")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HolaDesdeVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HolaDesdeVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4918")]
    public delegate void AgregarVentaCompletedEventHandler(object sender, AgregarVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4918")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591